Make strings untranslatable  (#2987)
* Make strings untranslatable #2980

* #2980 Fix for Uncaught ArgumentCountError: Too few arguments to function _x()

* Readd translatable strings #2980

* Add missing closing parentheses #2980